#!/bin/sh

KEYMAP_PATH=${LOCAL_KEYMAP_PATH}
rm -rf ${KEYMAP_PATH}/compat/japan
rm -rf ${KEYMAP_PATH}/compat/olpc
rm -rf ${KEYMAP_PATH}/compat/pc*
rm -rf ${KEYMAP_PATH}/compat/xtest

rm -rf ${KEYMAP_PATH}/geometry

rm -rf ${KEYMAP_PATH}/keycodes/amiga
rm -rf ${KEYMAP_PATH}/keycodes/ataritt
rm -rf ${KEYMAP_PATH}/keycodes/digital_vndr
rm -rf ${KEYMAP_PATH}/keycodes/empty
rm -rf ${KEYMAP_PATH}/keycodes/evdev
rm -rf ${KEYMAP_PATH}/keycodes/fujitsu
rm -rf ${KEYMAP_PATH}/keycodes/hp
rm -rf ${KEYMAP_PATH}/keycodes/ibm
rm -rf ${KEYMAP_PATH}/keycodes/macintosh
rm -rf ${KEYMAP_PATH}/keycodes/olpc
rm -rf ${KEYMAP_PATH}/keycodes/sgi_vndr
rm -rf ${KEYMAP_PATH}/keycodes/sony
rm -rf ${KEYMAP_PATH}/keycodes/sun
rm -rf ${KEYMAP_PATH}/keycodes/xfree*

rm -rf ${KEYMAP_PATH}/rules/HDR
rm -rf ${KEYMAP_PATH}/rules/base*
rm -rf ${KEYMAP_PATH}/rules/bin
rm -rf ${KEYMAP_PATH}/rules/compat
rm -rf ${KEYMAP_PATH}/rules/evdev.*
rm -rf ${KEYMAP_PATH}/rules/xfree*
rm -rf ${KEYMAP_PATH}/rules/xkb.dtd
rm -rf ${KEYMAP_PATH}/rules/xorg*

rm -rf ${KEYMAP_PATH}/symbols/af
rm -rf ${KEYMAP_PATH}/symbols/al
rm -rf ${KEYMAP_PATH}/symbols/am
rm -rf ${KEYMAP_PATH}/symbols/apl
rm -rf ${KEYMAP_PATH}/symbols/ara
rm -rf ${KEYMAP_PATH}/symbols/at
rm -rf ${KEYMAP_PATH}/symbols/az
rm -rf ${KEYMAP_PATH}/symbols/b*
rm -rf ${KEYMAP_PATH}/symbols/c*
rm -rf ${KEYMAP_PATH}/symbols/d*
rm -rf ${KEYMAP_PATH}/symbols/e*
rm -rf ${KEYMAP_PATH}/symbols/f*
rm -rf ${KEYMAP_PATH}/symbols/g*
rm -rf ${KEYMAP_PATH}/symbols/h*
rm -rf ${KEYMAP_PATH}/symbols/ie
rm -rf ${KEYMAP_PATH}/symbols/il
rm -rf ${KEYMAP_PATH}/symbols/in
rm -rf ${KEYMAP_PATH}/symbols/iq
rm -rf ${KEYMAP_PATH}/symbols/ir
rm -rf ${KEYMAP_PATH}/symbols/is
rm -rf ${KEYMAP_PATH}/symbols/it
rm -rf ${KEYMAP_PATH}/symbols/j*
rm -rf ${KEYMAP_PATH}/symbols/ke
rm -rf ${KEYMAP_PATH}/symbols/kg
rm -rf ${KEYMAP_PATH}/symbols/kh
rm -rf ${KEYMAP_PATH}/symbols/kpdl
rm -rf ${KEYMAP_PATH}/symbols/kr
rm -rf ${KEYMAP_PATH}/symbols/kz
rm -rf ${KEYMAP_PATH}/symbols/l*
rm -rf ${KEYMAP_PATH}/symbols/m*
rm -rf ${KEYMAP_PATH}/symbols/n*
rm -rf ${KEYMAP_PATH}/symbols/o*
rm -rf ${KEYMAP_PATH}/symbols/ph
rm -rf ${KEYMAP_PATH}/symbols/pk
rm -rf ${KEYMAP_PATH}/symbols/pl
rm -rf ${KEYMAP_PATH}/symbols/pt
rm -rf ${KEYMAP_PATH}/symbols/r*
rm -rf ${KEYMAP_PATH}/symbols/se
rm -rf ${KEYMAP_PATH}/symbols/sgi_vndr
rm -rf ${KEYMAP_PATH}/symbols/sharp_vndr
rm -rf ${KEYMAP_PATH}/symbols/shift
rm -rf ${KEYMAP_PATH}/symbols/si
rm -rf ${KEYMAP_PATH}/symbols/sk
rm -rf ${KEYMAP_PATH}/symbols/sn
rm -rf ${KEYMAP_PATH}/symbols/sony_vndr
rm -rf ${KEYMAP_PATH}/symbols/sun_vndr
rm -rf ${KEYMAP_PATH}/symbols/sy
rm -rf ${KEYMAP_PATH}/symbols/t*
rm -rf ${KEYMAP_PATH}/symbols/ua
rm -rf ${KEYMAP_PATH}/symbols/uz
rm -rf ${KEYMAP_PATH}/symbols/v*
rm -rf ${KEYMAP_PATH}/symbols/x*
rm -rf ${KEYMAP_PATH}/symbols/z*

rm -rf ${KEYMAP_PATH}/types/cancel
rm -rf ${KEYMAP_PATH}/types/caps
rm -rf ${KEYMAP_PATH}/types/default
rm -rf ${KEYMAP_PATH}/types/nokia
